### ISSUE TITLE
API Key support for civit_download

### ISSUE THREAD

**Issue by AlexMKramer** [saketh12/Auto1111SDK#13]
First off, I wanted to say that I really appreciate what you guys are doing!  This is much easier to implement in projects than trying to use GUI's APIs.  Now, onto the request:

Some models from CivitAI require an API key in order to download them.  An option for including your own api key would be a nice thing to have to easily download any of these models. 

Current errors when downloading these "restricted" models are: 
`ConnectionError: Error downloading the file: 401 Client Error: Unauthorized for url: https://civitai.com/api/download/models/329420`

Thanks!

**Comment by saketh12** [comment]
Hey, appreciate the compliments. When I pasted your download URL into my browser, it started downloading immediately? I don't know if that specific model requires an API key. We will look into adding that feature though, and if you want, you can also submit a PR with those changes.

**Comment by AlexMKramer** [comment]
The one I listed there does require an api key if downloading using the api. Through the website directly, I don't think there are many restrictions on downloading.

**Comment by superadi04** [comment]
Hey, we fixed this issue. the civit_download() function now has an optional parameter called "api_key" that you can pass your api key in. To use this updated version, pip install the repository as follows:

pip3 install git+https://github.com/saketh12/Auto1111SDK.git
