### ISSUE TITLE
How to get random seed value?

### ISSUE THREAD

**Issue by fastrocket** [saketh12/Auto1111SDK#16]
In diffusers, we can do the following to get the actual seed value if we pass in -1:

```
output = pipe.generate_txt2img(
    num_images=num_images,
    cfg_scale=cfg_scale,
    sampler_name=sampler_name,
    seed=seed,  # -1 for random
    prompt=llm_prompt + append_prompt,
    height=height,
    width=width,
    negative_prompt=negative_prompt,
    steps=steps
)

# After generation, retrieve the seed used
used_seed = pipe.scheduler.random_generator.seed
```

This doesn't work with this pipeline. How can we get the seed value?

**Comment by saketh12** [comment]
Hey, thanks for pointing this out, I will look into this now.

**Comment by saketh12** [comment]
Hey, just pushed a fix for this. Now, you can view all the data about your generation in a single line of code. Here's how:

```python
#After generation, retrieve the seed used
seed_used = pipe.pipeline_data.seed
```

If you print out pipe.pipeline_data, you will be able to view any other data about your generation (it is one long json containing all the information). 

I haven't pushed this yet to pypi, so just clone/pip install the latest version from this repo and it will work for you! Reopen this issue if you have any questions/concerns/comments.
