### ISSUE TITLE
Is there a way to load a VAE?

### ISSUE THREAD

**Issue by conanak99** [saketh12/Auto1111SDK#3]
Nice work on the library. Both the upscaler and StableDiffusionPipeline works as expected 👌 .

I don't see VAE in the roadmap or limitation, will they be supported too?

**Comment by superadi04** [comment]
hey, we'll be adding this soon

**Comment by saketh12** [comment]
Hi @conanak99 we just added support for loading custom VAE's. You can read more about how to do so here: https://flush-ai.gitbook.io/automatic-1111-sdk/pipelines/setting-a-custom-vae
